version: '3.3'
services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - es_data:/usr/share/elasticsearch/data/

  microblog:
    image: hardkoro/flask-microblog:latest
    depends_on:
      - db
    ports:
      - "8000:5000"
    env_file:
      - ./.env

volumes:
  postgres_data:
  es_data: