"""new fields in user model

Revision ID: 430273833bb6
Revises: f9ae36b6b203
Create Date: 2022-02-06 10:28:48.809571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430273833bb6'
down_revision = 'f9ae36b6b203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
