"""add language to posts

Revision ID: 722fde81c477
Revises: 807840d9bdbe
Create Date: 2022-02-11 08:16:36.033389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722fde81c477'
down_revision = '807840d9bdbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
