"""followers

Revision ID: 807840d9bdbe
Revises: 430273833bb6
Create Date: 2022-02-06 18:49:44.517307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807840d9bdbe'
down_revision = '430273833bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
